### ISSUE TITLE
Iframe not destroyed properly

### ISSUE THREAD

**Issue by ivanpopelyshev** [pixijs/pixi-examples-v2#2]
Run this one two times, duplicates of messages will appear in console.

I really don't know how to fix that, I tried it before

```js
var i = 0;
setInterval( function() {
    console.log('testing ' +(i++));
}, 1000);
```

**Comment by brettmeyer** [comment]
Thanks for the heads up.
Updated 'gh-pages' branch. IFrame is destroyed completely before loading in a new example and I'm no longer seeing the duplicate output in the console.

**Comment by ivanpopelyshev** [comment]
Awesome! We had that bug in previous examples too.

**Comment by GoodBoyDigital** [comment]
nice!
